In [ ]:
import pandas as pd   # Upload the dataset in google colab
from google.colab import files

In [ ]:
uploaded=files.upload()

Saving Kolkata_sentiment.csv to Kolkata_sentiment (4).csv


In [ ]:
df=pd.read_csv("Kolkata_sentiment.csv") # Storing the dataset in a data frame

In [ ]:
df.head()

Unnamed: 0  ... Quantification
0           0  ...        -0.6124
1           1  ...        -0.5267
2           2  ...        -0.6597
3           3  ...        -0.0460
4           4  ...         0.4215

[5 rows x 4 columns]

In [ ]:
!pip install tweet-preprocessor

##### Import the required libraries

In [ ]:
import pandas as pd
import numpy as np
import re
import nltk
import nltk.corpus
nltk.download('stopwords')
from nltk.corpus import stopwords
from termcolor import colored
from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.pipeline import Pipeline, FeatureUnion
from sklearn.metrics import f1_score, classification_report, accuracy_score,confusion_matrix
from sklearn.model_selection import train_test_split
import preprocessor as p
import pickle

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [ ]:
stop = stopwords.words('english')
def preprocess(data):
  data= p.clean(data)
  data= data.replace("[^a-zA-Z' ]","")
  data = ' '.join([word for word in data.split() if word not in stopwords.words("english")])
  return data

In [ ]:
x=df['Tweet']
y=df['Pos/Neg/Neu']

In [ ]:
len(x)

4347

In [ ]:
temp=[]

In [ ]:
for i in range(0,len(x)):
  a=x[i]
  b=preprocess(a)
  temp.append(b)

##### Checking if preprocessing is being done correctly or not


In [ ]:
x[1]

'coronavirus may give us the justice, which we failed to get from  government or supremecourt even. _news _india   _intl '

In [ ]:
temp[1]

'coronavirus may give us justice, failed get government supremecourt even. _news _india _intl'

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(temp, y, test_size=0.2)

In [ ]:
tf = TfidfVectorizer (analyzer='word',max_features=500000, stop_words=stopwords.words('english') , ngram_range=(1,3), lowercase=True)
#tf_transformer=tf.fit(corpus)
X_train=tf.fit_transform(X_train)
# Save vocab here !
pickle.dump(tf,open("tfidfv.pkl","wb"))
X_test=tf.transform(X_test)

In [ ]:
from google.colab import files
files.download('tfidfv.pkl')

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

In [ ]:
# pickle.dump(X_train , open("tfidf1.pkl", "wb"))

##### 1. Multinomial Naive Bayes Classifier

In [ ]:
from sklearn.naive_bayes import MultinomialNB
pipeline1 = Pipeline(
    [
        ('mnb', MultinomialNB())
    
                        
                  
])

In [ ]:
pipeline1.fit(X_train,y_train)

Pipeline(memory=None,
         steps=[('mnb',
                 MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True))],
         verbose=False)

In [ ]:
result = pipeline1.predict(X_test)
score = accuracy_score(result,y_test)
score

0.8413793103448276

In [ ]:
f1_score(result, y_test, average=None)

array([0.90482759, 0.2       , 0.54814815])

##### 2. Random Forest Classifier

In [ ]:
from sklearn.ensemble import RandomForestClassifier
pipeline2 = Pipeline(
    [
        ('rf',  RandomForestClassifier())
    
                        
                  
])

In [ ]:
pipeline2.fit(X_train,y_train)

Pipeline(memory=None,
         steps=[('rf',
                 RandomForestClassifier(bootstrap=True, ccp_alpha=0.0,
                                        class_weight=None, criterion='gini',
                                        max_depth=None, max_features='auto',
                                        max_leaf_nodes=None, max_samples=None,
                                        min_impurity_decrease=0.0,
                                        min_impurity_split=None,
                                        min_samples_leaf=1, min_samples_split=2,
                                        min_weight_fraction_leaf=0.0,
                                        n_estimators=100, n_jobs=None,
                                        oob_score=False, random_state=None,
                                        verbose=0, warm_start=False))],
         verbose=False)

In [ ]:
from sklearn.externals import joblib 
  
# Save the model as a pickle in a file 
joblib.dump(pipeline2, 'mod.pkl') 

['mod.pkl']

In [ ]:
result = pipeline2.predict(X_test)
score = accuracy_score(result,y_test)
score

0.8977011494252873

In [ ]:
f1_score(result, y_test, average=None)

array([0.93669065, 0.19047619, 0.7781155 ])

##### 3. Logistic Regression Classifier

In [ ]:
from sklearn.linear_model import LogisticRegression
pipeline3 = Pipeline(
    [
        ('lr',  LogisticRegression(C=10000, penalty='l2', multi_class='ovr'))
    
                        
                  
])


In [ ]:
pipeline3.fit(X_train,y_train)

/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)
/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression


Pipeline(memory=None,
         steps=[('lr',
                 LogisticRegression(C=10000, class_weight=None, dual=False,
                                    fit_intercept=True, intercept_scaling=1,
                                    l1_ratio=None, max_iter=100,
                                    multi_class='ovr', n_jobs=None,
                                    penalty='l2', random_state=None,
                                    solver='lbfgs', tol=0.0001, verbose=0,
                                    warm_start=False))],
         verbose=False)

In [ ]:
result = pipeline3.predict(X_test)
score = accuracy_score(result,y_test)
score

0.9137931034482759

In [ ]:
f1_score(result, y_test, average=None)

array([0.94845361, 0.26086957, 0.82451253])

##### 4. SGD Classifier

In [ ]:
from sklearn.linear_model import SGDClassifier
pipeline4 = Pipeline(
    [
        ('sgd',  SGDClassifier(alpha=.0001, max_iter=50, loss='log', penalty="elasticnet"))
    
                        
                  
])

In [ ]:
pipeline4.fit(X_train,y_train)

Pipeline(memory=None,
         steps=[('sgd',
                 SGDClassifier(alpha=0.0001, average=False, class_weight=None,
                               early_stopping=False, epsilon=0.1, eta0=0.0,
                               fit_intercept=True, l1_ratio=0.15,
                               learning_rate='optimal', loss='log', max_iter=50,
                               n_iter_no_change=5, n_jobs=None,
                               penalty='elasticnet', power_t=0.5,
                               random_state=None, shuffle=True, tol=0.001,
                               validation_fraction=0.1, verbose=0,
                               warm_start=False))],
         verbose=False)

In [ ]:
result = pipeline4.predict(X_test)
score = accuracy_score(result,y_test)
score

0.8448275862068966

In [ ]:
f1_score(result, y_test, average=None)

array([0.90756303, 0.2       , 0.58219178])

##### 5. XGBoost Classifier

In [ ]:
from xgboost import XGBClassifier
pipeline5 = Pipeline(
    [
        ('xg',  XGBClassifier(max_depth=3,n_estimators=300,learning_rate=0.1))
    
                        
                  
])

In [ ]:
pipeline5.fit(X_train,y_train)

Pipeline(memory=None,
         steps=[('xg',
                 XGBClassifier(base_score=0.5, booster='gbtree',
                               colsample_bylevel=1, colsample_bynode=1,
                               colsample_bytree=1, gamma=0, learning_rate=0.1,
                               max_delta_step=0, max_depth=3,
                               min_child_weight=1, missing=None,
                               n_estimators=300, n_jobs=1, nthread=None,
                               objective='multi:softprob', random_state=0,
                               reg_alpha=0, reg_lambda=1, scale_pos_weight=1,
                               seed=None, silent=None, subsample=1,
                               verbosity=1))],
         verbose=False)

In [ ]:
result = pipeline5.predict(X_test)
score = accuracy_score(result,y_test)
score

0.867816091954023

In [ ]:
f1_score(result, y_test, average=None)

array([0.92011412, 0.4       , 0.67532468])

In [ ]:
df['Pos/Neg/Neu'].value_counts(normalize=True)

negative    0.749942
positive    0.221762
neutral     0.028295
Name: Pos/Neg/Neu, dtype: float64

##### Checking the sentiment of a tweet

In [ ]:
z1="COVID-19 is not over yet!"
z1=preprocess(z1)

In [ ]:
z1

'COVID-19 yet!'

In [ ]:
s=[z1]


In [ ]:
s

['COVID-19 yet!']

In [ ]:
s=tf.transform(s)

In [ ]:
pipeline1.predict(s)

array(['negative'], dtype='<U8')